ASSUME CS:CODE,DS:DATA

DATA SEGMENT
    A DB 13D,10D,'THE GIVEN STRING IS PALINDROME $'
    B DB 13D,10D,'THE GIVEN STRING IS NOT PALINDROME $'
    C DB 'ENTER THE STRING- $'
    TEMP DB 00FFH DUP(?)
DATA ENDS

CODE SEGMENT
START:    MOV AX,DATA
    MOV DS,AX

    MOV AL,03H            ; CLEAR THE DOS SCREEN
    MOV AH,0
    INT 10H
   
    MOV AH,09H
    LEA DX,C
    INT 21H
   
    MOV CX,0000H            ; CLEAR THE COUNTER
    LEA SI,TEMP
BACK:    MOV AH,01H            ; TAKE STRING FROM USER AND SAVE IT IN "TEMP"
    MOV [SI],AL
    INT 21H
    INC SI
    INC CX
    CMP AL,13D
    JNZ BACK
    DEC CX
   
    MOV DX,CX      
    MOV AX,CX            ; MOVE COUNT IN AX
    MOV BL,02H
    DIV BL                ; COMPARISION SHOULD BE DONE HALF THE NO. OF CHARACTERS
    MOV CL,AL

    LEA SI,TEMP            ; SETTING THE POINTER SI TO FIRST CHARACTER OF STRING
    INC SI
    LEA DI,TEMP
    ADD DI,DX            ; SETTING THE POINTER DI TO LAST CHARACTER OF STRING

BACK1:    MOV AL,[SI]            ; MOVING THE CHARACTER POINTED BY SI IN AL
    MOV BL,[DI]            ; MOVING THE CHARACTER POINTED BY DI IN BL
    INC SI
    DEC DI
    CMP AL,BL            ; COMPARING AL AND BL
    JNZ SKIP
    DEC CL
    JNZ BACK1
    JMP SKIP2  

SKIP:     MOV AH,09H
    LEA DX,B
    INT 21H
    JMP EXIT

SKIP2:     MOV AH,09H
    LEA DX,A
    INT 21H

EXIT:    MOV AH,01H            ; HOLDING THE OUTPUT SCREEN
    INT 21H                ; GIVE ANY KEYBOARD INTERRUPT TO EXIT
    INT 03H

CODE ENDS
END START